language: python

python:
  - "2.7"

install: pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE phoenixdb;" -U postgres
  - psql -c "CREATE SCHEMA compromised_processed;" -U postgres

script:
  - cd Validation
  - python validation.py
